# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020-2024 Intel Corporation

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Change this namespace to match with namespace in config/default/kustomization.yaml
namespace: intel-ethernet-operator-system
resources:
- flowconfig-manager.yaml

patchesStrategicMerge:
- add_volumes.yaml
images:
- name: daemon-image
  newName: ger-is-registry.caas.intel.com/cno/lalrafax/intel-ethernet-operator-flowconfig-daemon
  newTag: 3.0.2
- name: dcf-tool
  newName: ger-is-registry.caas.intel.com/cno/lalrafax/uft
  newTag: v22.07
