# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020-2024 Intel Corporation

apiVersion: v1
kind: ConfigMap
metadata:
  name: labeler-config
  namespace: {{ .ETHERNET_NAMESPACE }}
immutable: false
data:
  configMap: |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: supported-cvl-devices
      namespace: {{ .ETHERNET_NAMESPACE }}
    immutable: false
    data:
      devices.json: |
        {
            "E810-CQDA2": {
                "VendorID": "8086", "Class": "02", "SubClass": "00", "DeviceID": "1592"
            },
            "E810-2CQDA2": {
                "VendorID": "8086", "Class": "02", "SubClass": "00", "DeviceID": "1592"
            },
            "E810-XXVDA2": {
                "VendorID": "8086", "Class": "02", "SubClass": "00", "DeviceID": "159b"
            },
            "E810-XXVDA4": {
                "VendorID": "8086", "Class": "02", "SubClass": "00", "DeviceID": "1593"
            },
            "X710-SFP+": {
                "VendorID": "8086", "Class": "02", "SubClass": "00", "DeviceID": "1572"
            }
        }
  serviceAccount: |
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: cvl-discovery
      namespace: "{{ .ETHERNET_NAMESPACE }}"
  clusterRole: |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: cvl-discovery
    rules:
      - apiGroups: [""]
        resources: ["nodes"]
        verbs: ["get", "update"]
  clusterRoleBinding: |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: cvl-discovery
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: cvl-discovery
    subjects:
      - kind: ServiceAccount
        name: cvl-discovery
        namespace: "{{ .ETHERNET_NAMESPACE }}"
  daemonSet: |
    apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      labels:
        app: cvl-discovery
      name: cvl-discovery
      namespace: {{ .ETHERNET_NAMESPACE }}
    spec:
      minReadySeconds: 10
      selector:
        matchLabels:
          app: cvl-discovery
      template:
        metadata:
          labels:
            app: cvl-discovery
          name: cvl-discovery
        spec:
          serviceAccount: cvl-discovery
          serviceAccountName: cvl-discovery
          containers:
            - image: {{ .ETHERNET_NODE_LABELER_IMAGE }}
              imagePullPolicy: IfNotPresent
              name: cvl-discovery
              securityContext:
                readOnlyRootFilesystem: true
              volumeMounts:
                - name: config-volume
                  mountPath: "/labeler-workspace/devices.json"
                  subPath: devices.json
                  readOnly: true
              env:
                - name: NODENAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
                - name: CVLLABEL
                  value: "ethernet.intel.com/intel-ethernet-cvl-present"
                - name: FVLLABEL
                  value: "ethernet.intel.com/intel-ethernet-fvl-present"
          volumes:
            - name: config-volume
              configMap:
                name: supported-cvl-devices
