# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020-2024 Intel Corporation

name: e2e-tests-template

inputs:
  target:
    required: true
  secret:
    required: true
  tests_token:
    required: true

runs:
  using: composite
  steps:
    - name: Checkout tests repository
      uses: actions/checkout@v4
      with:
        repository: intel-collab/applications.orchestration.operators.tests
        ref: main
        token: ${{ inputs.tests_token }}
        path: ${{ env.TESTS_REPO }}

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.21"

    - uses: azure/setup-kubectl@v3
      with:
        version: "v1.29.0"

    - uses: redhat-actions/openshift-tools-installer@v1
      with:
        oc: "4.14"

    - name: Setup yq
      uses: supplypike/setup-bin@v3
      with:
        uri: "https://github.com/mikefarah/yq/releases/download/v4.40.5/yq_linux_amd64"
        name: yq
        version: "v4.40.5"

    - name: Save kubeconfig to file
      shell: bash
      run: echo "${{ inputs.secret }}" > ${{ inputs.target }}-kubeconfig

    - name: Deploy local webserver
      shell: bash
      run: |
        sed -i 's#image: .*#image: ${{ env.WEBSERVER }}#' deployment.yaml
        sed -i '/nodeName:/d' deployment.yaml
        $K8S_BIN apply -f deployment.yaml
        $K8S_BIN apply -f service.yaml
      working-directory: ${{ env.TESTS_REPO }}/webserver

    - name: Prepare Makefile
      shell: bash
      run: |
        cp Makefile Makefile-${{ inputs.target }}
        sed -i "s/| tee test_logs.txt/| tee test_logs_${{ inputs.target }}.txt/" Makefile-${{ inputs.target }}
        sed -i "s#/usr/bin/yq#yq#" Makefile-${{ inputs.target }}
        sed -i "s#junit-report \$(PWD)/junit.xml#junit-report \$(PWD)/junit_${{ inputs.target }}.xml#" Makefile-${{ inputs.target }}
        cp ci/test-config-ghactions.yaml test-config.yaml
      working-directory: ${{ env.TESTS_REPO }}/e2e-tests/intel-ethernet-operator

    - name: Deploy operator
      shell: bash
      run: |
        make -f Makefile-${{ inputs.target }} undeploy_operator
        make -f Makefile-${{ inputs.target }} deploy_operator
        sleep 10s
      working-directory: ${{ env.TESTS_REPO }}/e2e-tests/intel-ethernet-operator

    - name: Run test suite
      shell: bash
      run: |
        make -f Makefile-${{ inputs.target }} test
      working-directory: ${{ env.TESTS_REPO }}/e2e-tests/intel-ethernet-operator

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.target }}-test-results
        path: |
          ${{ env.TESTS_REPO }}/e2e-tests/intel-ethernet-operator/test_logs_${{ inputs.target }}.txt
          ${{ env.TESTS_REPO }}/e2e-tests/intel-ethernet-operator/junit_${{ inputs.target }}.xml

    - name: Publish test report
      uses: mikepenz/action-junit-report@v4
      if: always()
      with:
        report_paths: ${{ env.TESTS_REPO }}/e2e-tests/intel-ethernet-operator/junit_${{ inputs.target }}.xml
