{{/*
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020-2024 Intel Corporation
*/}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "intel-ethernet-operator.managerConfigMap" . }}
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: 8ee6d2ed.intel.com

{{- if .Values.webhookServerConfiguration.mTLSWebhook.enable -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "intel-ethernet-operator.mTLSWebhookConfig" . }}
data:
  enable-webhook-mtls: "true"
{{- end }}