{{/*
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020-2024 Intel Corporation
*/}}

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "intel-ethernet-operator.roleBinding" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "intel-ethernet-operator.role" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "intel-ethernet-operator.serviceAccount" . }}
