{{/*
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020-2024 Intel Corporation
*/}}

{{- if and .Values.webhookServerConfiguration.enable (not .Values.webhookServerConfiguration.useCertManager) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "intel-ethernet-operator.webhookCertsSecret" . }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get .Values.webhookServerConfiguration.serverCertFilepath | b64enc | quote }}
  tls.key: {{ .Files.Get .Values.webhookServerConfiguration.serverKeyFilepath | b64enc | quote }}
{{- end -}}

{{ if and .Values.webhookServerConfiguration.mTLSWebhook.enable (not (empty .Values.webhookServerConfiguration.mTLSWebhook.clientCaFilepath)) -}}
---
apiVersion: v1
kind: Secret
metadata:
  # change this?
  name: {{ include "intel-ethernet-operator.mTLSWebhookCASecret" . }}
data:
  ca.crt: {{ .Files.Get .Values.webhookServerConfiguration.mTLSWebhook.clientCaFilepath | b64enc | quote }}
{{- end }}