{{/*
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020-2024 Intel Corporation
*/}}

apiVersion: v1
kind: ServiceAccount
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
metadata:
  name: {{ include "intel-ethernet-operator.serviceAccount" . }}
  labels:
    {{- include "intel-ethernet-operator.labels" . | nindent 4 }}
